services:
  db:
    image: postgres
    environment:
      - POSTGRES_USER=catanatron
      - POSTGRES_PASSWORD=victorypoint
      - POSTGRES_DB=catanatron_db
    ports:
      - 5432:5432
    volumes:
      - ./db-data:/var/lib/postgresql
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -d postgresql://catanatron:victorypoint@db:5432/catanatron_db",
        ]
      interval: 5s
      timeout: 5s
      retries: 5
  server:
    build:
      context: .
      dockerfile: Dockerfile.web
    environment:
      - DATABASE_URL=postgresql://catanatron:victorypoint@db:5432/catanatron_db
      - PYTHONUNBUFFERED=1
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - NEGOTIATION_ADVICE_MODEL=gpt-4o-mini
    ports:
      - 5001:5001
    stdin_open: true
    restart: always
    volumes:
      - .:/app
    depends_on:
      db:
        condition: service_healthy
  react-ui:
    build: ./ui
    ports:
      - 3000:3000
    stdin_open: true
    environment:
      - CTRON_API_URL=http://localhost:5001
    volumes:
      - /app/node_modules
      - ./ui:/app
